# -*- coding: utf-8 -*-
"""OnlineShoppigML61

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbY_GceH4tV6Pe4_8ungGR-sEHreYqiv

## Online Shopping Behavior Phase 1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import pickle
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from sklearn.model_selection import GridSearchCV

"""# Data Loading:"""

from google.colab import files
uploaded = files.upload()

df = pd.read_excel("Shopping.xlsx")

cols = df.select_dtypes(include=['object']).columns
print(cols)

"""#Data Exploration:"""

df.head()

"""

### Key

- Age:
  - 1 = Less than 18
  - 2 = 18–24
  - 3 = 25–34
  - 4 = 35–44
- Gender:
  - 1 = Male
  - 2 = Female
- Online Shopping Frequency (per month):
  - 1 = Rarely
  - 2 = 1–2 times
  - 3 = 3–5 times
  - 4 = More than 5 times
- Device Used for Online Shopping:
  - 1 = Mobile
  - 2 = Laptop
  - 3 = Tablet

- Time Spent Browsing Before Purchase:
  - 1 = Less than 10 minutes
  - 2 = 10–30 minutes
  - 3 = 30–60 minutes
  - 4 = More than 1 hour

- Reads Reviews Before Purchasing:
  - 1 = Always
  - 2 = Sometimes
  - 3 = Rarely
  - 4 = Never

- Compares Prices Across Websites:
  - 1 = Always
  - 2 = Sometimes
  - 3 = Rarely
  - 4 = Never

- Influence of Discounts and Offers:
  - 1 = A lot
  - 2 = Somewhat
  - 3 = A little
  - 4 = Not at all

- Doesnt Complete Purchase:
  - 1 = Yes
  - 2 = No

- Most Important Purchase Factor:
  - 1 = Price
  - 2 = Quality
  - 3 = Reviews
  - 4 = Delivery speed
  - 5 = Brand

- Completes Purchase After Browsing (Target Variable):
  - 1 = Yes
  - 2 = No

"""

# Dataset information
df.info()

#Number of rows and columns
df.shape

df.describe()

# Print out the number of data for target feature (output)
df_clean = df.copy()

df_clean['Completes Purchase After Browsing'].value_counts()

"""Checking for missing values:"""

df.isnull().sum()

"""No missing values were found.

Checking for duplicates:
"""

df.duplicated().sum()

"""Checking for outliers:"""

df.drop("Id", axis=1).boxplot(figsize=(10,5))
plt.xticks(rotation=90)
plt.show()

"""No significant outliers were found, since the data is based on predefined categorical responses (scale 1–5),the observed values are valid and do not represent true anomalies.

##Cleaning The Data:
"""

#Make a copy of data
df_clean = df.copy()

#Remove extra spaces
df_clean.columns = df_clean.columns.str.strip()

# Checking column names after cleaning to confirm changes
print(df_clean.columns)

df_clean.head(10)

df_clean.shape

"""#Set Target"""

# Print distribution of target variable
df_clean["Completes Purchase After Browsing"]

# Check target distribution
df_clean["Completes Purchase After Browsing"].value_counts()

"""Key:
- Completes Purchase After Browsing:
  - 1 = Yes
  - 2 = No
"""

num_cols = df_clean.select_dtypes(include=np.number).columns
num_cols

"""# Visualization

Pie charts were used to visualize the distribution of key categorical variables such as age, gender, and shopping frequency, providing insights into user behavior.
"""

# Map Age categories
age_labels = df_clean["Age"].map({
    1: "Less than 18",
    2: "18–24",
    3: "25–34",
    4: "35–44"
})

# Plot
age_labels.value_counts().plot.pie(
    autopct='%1.1f%%',
    figsize=(5,5)
)

plt.title("Age Distribution")
plt.ylabel("")
plt.show()

gender_labels = df_clean["Gender"].map({
    1: "Male",
    2: "Female"
})

# Plot
gender_labels.value_counts().plot.pie(
    autopct='%1.1f%%',
    figsize=(5,5)
)

plt.title("Gender Distribution")
plt.ylabel("")
plt.show()

# Map Shopping Frequency
freq_labels = df_clean["Online Shopping Frequency (Monthly)"].map({
    1: "Rarely",
    2: "1–2 times",
    3: "3–5 times",
    4: "More than 5 times"
})

# Plot
freq_labels.value_counts().plot.pie(
    autopct='%1.1f%%',
    figsize=(5,5)
)

plt.title("Online Shopping Frequency")
plt.ylabel("")
plt.show()

df_clean.hist(figsize=(35,20))
plt.show()

"""*   1:Male
*   2:Female

*   1 = Less than 18
*   2 = 18–24



*   3 = 25–34
*   4 = 35–44
"""

sns.countplot(x=df_clean["Completes Purchase After Browsing"])
plt.title("Target Distribution")
plt.show()

"""The countplot shows the distribution of the target variable "Completes Purchase After Browsing".

It can be observed that most users tend to complete their purchases after browsing (class 1), while a smaller portion of users do not complete their purchases (class 2).

This indicates that the dataset is slightly imbalanced, with more positive purchase outcomes than negative ones.
"""

sns.countplot(
    x='Online Shopping Frequency (Monthly)',
    data=df_clean
)

plt.title("Online Shopping Frequency Distribution")
plt.xlabel("Online Shopping Frequency (Monthly)")
plt.ylabel("Count")
plt.show()

sns.countplot( x='Completes Purchase After Browsing', hue='Online Shopping Frequency (Monthly)',data=df_clean)

plt.title("Purchase Completion vs Shopping Frequency")
plt.show()

"""The plot shows that most users shop online infrequently (1–2 times per month), and these users also make up the majority of those who complete purchases after browsing. Higher-frequency shoppers are fewer in number and show lower counts in both completion and non-completion categories."""

sns.countplot(x='Completes Purchase After Browsing',hue='Age',data=df_clean)
plt.title("Purchase Completion by Age")
plt.xlabel("Completes Purchase After Browsing")
plt.ylabel("Count")
plt.show()

sns.countplot(x='Completes Purchase After Browsing',hue='Gender',data=df_clean)
plt.title("Purchase Completion by Gender")
plt.xlabel("Completes Purchase After Browsing")
plt.ylabel("Count")
plt.show()

"""#Data Splitting (Train-Test Split)

"""

X = df_clean.iloc[:, :-1].values
y = df_clean.iloc[:, 11].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

"""#Modeling

#LogisticRegression
"""

classifier = LogisticRegression()
classifier.fit(X_train, y_train)

y_train_pred = classifier.predict(X_train)
y_pred = classifier.predict(X_test)

print('Training Accuracy : ', accuracy_score(y_train,y_train_pred))
print('Test Accuracy : ', accuracy_score(y_test, y_pred))

print("Classification Report:")
print(classification_report(y_test, y_pred))

result = confusion_matrix(y_test, y_pred)
sns.heatmap(result, annot=True, cmap='crest', fmt="g", linewidth=2)
plt.xlabel('Predicted labels')
plt.ylabel('True labels')
plt.title("Logistic Regression Confusion Matrix")
plt.show()

"""Logistic Regression achieved a training accuracy of 67% and a test accuracy of 64%, showing no significant overfitting since the values are close. However, the overall accuracy is moderate, which suggests that the model may suffer from underfitting due to its simplicity.

The classification report indicates that the model performs well in predicting Class 1, with a high recall of 0.84. In contrast, the performance on Class 2 is weaker, with a recall of only 0.33, meaning the model fails to correctly identify many instances of this class.

Overall, the model shows unbalanced performance between the classes and may not be suitable for capturing the complexity of the dataset.

#Decision Tree
"""

base_model2 = DecisionTreeClassifier(criterion='entropy',
                                    max_depth=1)

base_model2.fit(X_train, y_train)

stumptrainAcc = base_model2.score(X_train, y_train)
print("Training Accuracy:", stumptrainAcc)
stumptestAcc = base_model2.score(X_test, y_test)
print("Accuracy:", stumptestAcc)

y_pred_DT = base_model2.predict(X_test)
print("Decision Tree Report:")
print(classification_report(y_test, y_pred_DT))

y_pred_DT = base_model2.predict(X_test)
cm = confusion_matrix(y_test, y_pred_DT)

sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted labels")
plt.ylabel("True labels")
plt.title("Decision Tree Confusion Matrix")
plt.show()

"""Decision Tree achieved a training accuracy of about 60% and a test accuracy of 60.8%, indicating that there is no significant overfitting since both values are very close. However, the overall performance is relatively low.

The classification report shows that the model predicts Class 1 very well, with a recall of 1.00, meaning it correctly identifies all instances of this class. However, it completely fails to predict Class 2, with a recall of 0.00, indicating that the model is biased toward one class.

Overall, the model demonstrates poor generalization and unbalanced performance, making it unreliable for this dataset.

#Random Forest
"""

rf = RandomForestClassifier(n_estimators=100,
                            criterion='gini',
                            random_state=42)

rf.fit(X_train, y_train)

trainrfAcc = rf.score(X_train, y_train)
print("Training Accuracy:", trainrfAcc)
testrfAcc = rf.score(X_test, y_test)
print("Testing Accuracy:", testrfAcc)

y_pred_RF = rf.predict(X_test)
print("Random Forest Report:")
print(classification_report(y_test, y_pred_RF))

y_pred_RF = rf.predict(X_test)
cm_rf = confusion_matrix(y_test, y_pred_RF)
sns.heatmap(cm_rf, annot=True, fmt="d", cmap="Greens")
plt.xlabel("Predicted labels")
plt.ylabel("True labels")
plt.title("Random Forest Confusion Matrix")
plt.show()

"""Random Forest achieved a training accuracy of 100% and a test accuracy of 59.2%. The perfect training accuracy indicates that the model has memorized the training data, which is a clear sign of overfitting.

The classification report shows moderate performance, where the model predicts Class 1 better (recall = 0.75) compared to Class 2 (recall = 0.35). This indicates that the model still struggles with correctly identifying Class 2, although it performs better than simpler models.

Overall, despite being a complex model, Random Forest does not generalize well to unseen data and shows clear overfitting, making its performance less reliable.

#Standard Scaler(RandomForest)
"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

rf_scaled = RandomForestClassifier(random_state=42)

rf_scaled.fit(X_train_scaled, y_train)

y_train_pred_RF = rf_scaled.predict(X_train_scaled)
y_pred_RF_After = rf_scaled.predict(X_test_scaled)

from sklearn.metrics import accuracy_score
print("Training Accuracy after scaling:",accuracy_score(y_train, y_train_pred_RF))
print("Test Accuracy after scaling:", accuracy_score(y_test, y_pred_RF_After))

print("Classification Report:")
print(classification_report(y_test, y_pred_RF_After ))

print("=== Random Forest Comparison ===")
print(f"Accuracy Before Scaling : {testrfAcc:.3f}")
print(f"Accuracy After Scaling  : {accuracy_score(y_test, y_pred_RF):.3f}")

"""After applying StandardScaler to the Random Forest model, no change in performance was observed, as the test accuracy remained the same before and after scaling (0.592). Therefore, feature scaling will be applied next to the second worst model to further evaluate its impact.

#Standard Scaler(Decision Tree)
"""

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

dt_scaled = DecisionTreeClassifier(random_state=42)

dt_scaled.fit(X_train_scaled, y_train)

y_train_pred_DT = dt_scaled.predict(X_train_scaled)

y_pred_DT_After = dt_scaled.predict(X_test_scaled)

print("Training Accuracy after scaling:", accuracy_score(y_train, y_train_pred_DT))

print("Test Accuracy after scaling:", accuracy_score(y_test, y_pred_DT_After))

print("\nClassification Report:")

print(classification_report(y_test, y_pred_DT_After))

print("=== Decision Tree Comparison ===")
print(f"Accuracy Before Scaling : {accuracy_score(y_test, y_pred_DT):.3f}")
print(f"Accuracy After Scaling  : {accuracy_score(y_test, y_pred_DT_After):.3f}")

"""After applying StandardScaler to the Decision Tree model, the performance changed noticeably, where the test accuracy decreased from around 60% to 44%. This indicates that scaling negatively affected the model in this case. Although Decision Trees are generally not sensitive to feature scaling, the transformation of feature values can sometimes impact how the tree performs splits, leading to different results.

#GridSearchCV
"""

classifier = LogisticRegression(max_iter=1000)

param_grid = {
    'C': [0.1, 1, 10],
}

grid = GridSearchCV(classifier, param_grid, cv=5)
grid.fit(X_train, y_train)

print("Best score:", grid.best_score_)
print("Best parameters:", grid.best_params_)

best_lr = grid.best_estimator_

print("Training Accuracy:", best_lr.score(X_train, y_train))
print("Testing Accuracy:", best_lr.score(X_test, y_test))

"""Decision Tree"""

param_grid = {
    'max_depth': [1, 3, 5, 10],
    'criterion': ['gini', 'entropy']
}

grid = GridSearchCV(base_model2, param_grid, cv=5)
grid.fit(X_train, y_train)

print("Best score:", grid.best_score_)
print("Best parameters:", grid.best_params_)


base_model2 = grid.best_estimator_

print("Training Accuracy:", base_model2.score(X_train, y_train))
print("Testing Accuracy:", base_model2.score(X_test, y_test))

"""Random Forest"""

param_grid = {
    'n_estimators': [10, 50, 100],
    'max_depth': [3, 5, 10]
}

grid = GridSearchCV(rf, param_grid, cv=5)
grid.fit(X_train, y_train)

print("Best score:", grid.best_score_)
print("Best parameters:", grid.best_params_)

rf = grid.best_estimator_

print("Training Accuracy:", rf.score(X_train, y_train))
print("Testing Accuracy:", rf.score(X_test, y_test))

print("\n=== Comparison Before vs After Tuning ===")

# Logistic Regression
print("Logistic Regression Before:", accuracy_score(y_test, y_pred))
print("Logistic Regression After :", best_lr.score(X_test, y_test))
print("\n==========================================================")
# Decision Tree
print("Decision Tree Before:", accuracy_score(y_test, y_pred_DT))
print("Decision Tree After :", base_model2.score(X_test, y_test))
print("\n==========================================================")
# Random Forest
print("Random Forest Before:", accuracy_score(y_test, y_pred_RF_After))
print("Accuracy After Scaling :", rf.score(X_test, y_test))

"""After applying hyperparameter tuning using GridSearchCV, the model performance was evaluated before and after tuning. The results showed that Random Forest improved from 0.592 to 0.624, indicating better generalization. In contrast, Logistic Regression showed no significant improvement, and Decision Tree remained unchanged. This suggests that tuning was more effective for Random Forest compared to the other models.

**pickle**
"""

pickle.dump(best_lr,open('best_lr.pkl','wb'))
pickle.dump(base_model2,open('base_model2.pkl','wb'))
pickle.dump(rf,open('rf.pkl','wb'))


files.download('classifier.pkl')
files.download('base_model2.pkl')
files.download('rf.pkl')